// Generated by npm run images:optimize. Do not edit manually.
export const projectImages = {
  "oboxle": "/projects/optimized/oboxle.057b41791a22.webp",
  "findr": "/projects/optimized/findr.56cf0d928a14.webp",
  "ubcschedules": "/projects/optimized/ubcschedules.5e420c602bbf.webp",
  "notetakingapp": "/projects/optimized/notetakingapp.f35fb2bd17d3.webp"
} as const
