import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import sharp from 'sharp'

const names = ['oboxle', 'findr', 'ubcschedules', 'notetakingapp']
const output = new URL('../public/projects/optimized/', import.meta.url)
await mkdir(output, { recursive: true })
const images = {}

for (const name of names) {
  const source = await readFile(new URL(`../assets/projects/${name}.png`, import.meta.url))
  const optimized = await sharp(source)
    .resize({ width: 1200, withoutEnlargement: true })
    .webp({ quality: 85, effort: 6 })
    .toBuffer()
  const hash = createHash('sha256').update(optimized).digest('hex').slice(0, 12)
  const filename = `${name}.${hash}.webp`
  await writeFile(new URL(filename, output), optimized)
  images[name] = `/projects/optimized/${filename}`
  console.log(`${name}: ${source.length} → ${optimized.length} bytes`)
}

await writeFile(new URL('../src/content/project-images.ts', import.meta.url),
  `// Generated by npm run images:optimize. Do not edit manually.\nexport const projectImages = ${JSON.stringify(images, null, 2)} as const\n`)
